/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package adivinanumero;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

public class Adivina extends javax.swing.JFrame {
    
    //Para el numero aleatorio
Random numero = new Random();

        int aleatorio=numero.nextInt(1000);
        String mens=String.valueOf(aleatorio);

   
    public Adivina() {
        
        initComponents();
        
      
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlJuego = new javax.swing.JPanel();
        lblMensaje = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnOkey = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMensaje.setText("Tengo un numero entre 1 y 1000. Puede usted adivinarlo?");

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        btnOkey.setText("OK");
        btnOkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlJuegoLayout = new javax.swing.GroupLayout(pnlJuego);
        pnlJuego.setLayout(pnlJuegoLayout);
        pnlJuegoLayout.setHorizontalGroup(
            pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJuegoLayout.createSequentialGroup()
                .addGroup(pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJuegoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblMensaje))
                    .addGroup(pnlJuegoLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlJuegoLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnOkey)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pnlJuegoLayout.setVerticalGroup(
            pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJuegoLayout.createSequentialGroup()
                .addComponent(lblMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOkey)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(pnlJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
       

       
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btnOkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkeyActionPerformed

         String numeroUsuario=txtNumero.getText();
         
       int numero1=Integer.parseInt(numeroUsuario);
       
        
       if(numero1==aleatorio){
            
        pnlJuego.setBackground(Color.ORANGE); 
        JOptionPane.showMessageDialog(rootPane, "CORRECTO");
        
        }else if(numero1 < aleatorio){
        int a=aleatorio-numero1;
        if(a>=100){
        pnlJuego.setBackground(Color.BLUE); 
        
        int iconoAdvertencia = JOptionPane.WARNING_MESSAGE;
         JOptionPane.showMessageDialog(rootPane, "Escriba numero mas alto", "PISTA!", iconoAdvertencia);
        
        }else if(a<100){
       int iconoAdvertencia = JOptionPane.WARNING_MESSAGE;
         pnlJuego.setBackground(Color.RED); 
        JOptionPane.showMessageDialog(rootPane, "Escriba numero mas bajo", "PISTA!", iconoAdvertencia);        
        }
        }else if(numero1>aleatorio){
        int a=numero1-aleatorio;
        if(a>=100){
        pnlJuego.setBackground(Color.BLUE); 
        int iconoAdvertencia = JOptionPane.WARNING_MESSAGE;
         JOptionPane.showMessageDialog(rootPane, "Escriba numero mas alto", "PISTA!", iconoAdvertencia);
        }else if(a<100){
            pnlJuego.setBackground(Color.RED); 
       int iconoAdvertencia = JOptionPane.WARNING_MESSAGE;
         JOptionPane.showMessageDialog(rootPane, "Escriba numero mas bajo", "PISTA!", iconoAdvertencia);      
        
        }
        
        }
  /* int numero = Integer.parseInt(txtNumero.getText());
    numero=1;*/
    
  /*int aleatorio=(int)(Math.random()*1000);
       int numero=0;
       int contador=0;   		
  
  do{
			
               contador++;

	     numero=Integer.parseInt(txtNumero.getText());

			if(aleatorio<numero){
                            
            int iconoAdvertencia = JOptionPane.WARNING_MESSAGE;
            JOptionPane.showMessageDialog(rootPane, "Ingrese Número mas bajo", "PISTA!", iconoAdvertencia);
				

               
			}else if(aleatorio>numero){
                            
                            int iconoAdvertencia2 = JOptionPane.WARNING_MESSAGE;
                            JOptionPane.showMessageDialog(rootPane, "Ingrese Número mas alto", "PISTA!", iconoAdvertencia2);

				
                     
			}

		}while(numero!=aleatorio);

		JOptionPane.showMessageDialog(null, "Adivinaste en" + contador + " intentos");

 
    
    */
    
    }//GEN-LAST:event_btnOkeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adivina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adivina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adivina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adivina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adivina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkey;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JPanel pnlJuego;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
